#注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#服务端口
server:
  port: 8762
      
spring:
  application:
    #服务名
    name: client
  #MQ配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  #BUS配置
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  zipkin:
    base-url: http://localhost:9411
#BUS配置
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

        
 
