eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 8764

spring:
  application:
    #服务名
    name: service-zuul
  #MQ配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  #BUS配置
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
#BUS配置
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
        
#路由配置
zuul:
    routes:
        api-a:
            path: /api-a/**
            serviceId: service-ribbon
        api-b:
            path: /api-b/**
            serviceId: service-feign
